version: 1.2

tools:
  # =============================================================================
  # MODULES - Individual tool-specific task collections
  # =============================================================================

  - name: ww-annotsv
    subclass: WDL
    primaryDescriptorPath: /modules/ww-annotsv/ww-annotsv.wdl
    readMePath: /modules/ww-annotsv/README.md
    authors:
      - name: Taylor Firman
        email: tfirman@fredhutch.org
        role: Research Informatics Data Scientist
        affiliation: Fred Hutch Cancer Center
        orcid: 0009-0002-2052-1084
    topic: "WDL module for structural variant annotation using AnnotSV"

  - name: ww-annovar
    subclass: WDL
    primaryDescriptorPath: /modules/ww-annovar/ww-annovar.wdl
    readMePath: /modules/ww-annovar/README.md
    authors:
      - name: Taylor Firman
        email: tfirman@fredhutch.org
        role: Research Informatics Data Scientist
        affiliation: Fred Hutch Cancer Center
        orcid: 0009-0002-2052-1084
    topic: "WDL module for variant annotation using Annovar"
